version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
  minesweeper-api:
    image: minesweeper-api-image
    container_name: minesweeper-api
    ports:
      - 8080:8080
    depends_on:
      - mongo